/* eslint-disable @next/next/no-page-custom-font */
export default function Head() {
  return (
    <>
      <title>מתייעלים</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon/favicon.ico" />
    </>
  );
}
